phraseapp:
  access_token: 
  project_id: b25e10eb57aa0ee3ea44a4b271f2fde8
  file_format: yml
  push:
    sources:
    - file: locale/<locale_name>.yml
      params:
        files_format: yml
  pull:
    targets:
    - file: locale/<locale_name>.yml
      params:
        files_format: yml
