phraseapp:
  access_token: c747ba1ee597ae8d2ec4a731eb26bd095f395a65549ff3956bb5d09210f66f32
  project_id: 7e0c0b0aac821629dda2555a2749cffb
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
