phraseapp:
  access_token: 63f0269aeea4af5d56feae7fec221fd45ce083cd
  project_id: f5f9c63f61e3297a86ac318a7c9dfbcb
  file_format: json
  push:
    sources:
    - file: locale/<locale_name>.json
      params:
        files_format: json
  pull:
    targets:
    - file: locale/<locale_name>.json
      params:
        files_format: json
